"""empty message

Revision ID: 4d52d5579ec7
Revises: 6fe9fab73ec7
Create Date: 2016-01-05 11:01:24.327636

"""

# revision identifiers, used by Alembic.
revision = '4d52d5579ec7'
down_revision = '6fe9fab73ec7'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('password', sa.String(length=180), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'password')
    ### end Alembic commands ###
