"""Hash password

Revision ID: 6fe9fab73ec7
Revises: 261521e51587
Create Date: 2016-01-05 10:20:12.659852

"""

# revision identifiers, used by Alembic.
revision = '6fe9fab73ec7'
down_revision = '261521e51587'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'password')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('password', sa.VARCHAR(length=20), autoincrement=False, nullable=True))
    ### end Alembic commands ###
