"""Add user to comments table

Revision ID: 9bf5bf5ab706
Revises: 4d52d5579ec7
Create Date: 2016-01-06 11:46:54.929171

"""

# revision identifiers, used by Alembic.
revision = '9bf5bf5ab706'
down_revision = '4d52d5579ec7'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comments', sa.Column('username', sa.String(length=20), nullable=False))
    op.alter_column('users', 'email',
               existing_type=sa.VARCHAR(length=30),
               nullable=False)
    op.alter_column('users', 'password',
               existing_type=sa.VARCHAR(length=180),
               nullable=False)
    op.alter_column('users', 'username',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'username',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
    op.alter_column('users', 'password',
               existing_type=sa.VARCHAR(length=180),
               nullable=True)
    op.alter_column('users', 'email',
               existing_type=sa.VARCHAR(length=30),
               nullable=True)
    op.drop_column('comments', 'username')
    ### end Alembic commands ###
