"""Receive image_path as identifier instead

Revision ID: cc01f345ceb7
Revises: d782b5fe2eae
Create Date: 2015-12-29 15:16:01.785492

"""

# revision identifiers, used by Alembic.
revision = 'cc01f345ceb7'
down_revision = 'd782b5fe2eae'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comments', sa.Column('image_path', sa.String(length=160), nullable=False))
    op.drop_column('comments', 'chapter')
    op.drop_column('comments', 'page')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comments', sa.Column('page', sa.VARCHAR(length=80), autoincrement=False, nullable=False))
    op.add_column('comments', sa.Column('chapter', sa.VARCHAR(length=80), autoincrement=False, nullable=False))
    op.drop_column('comments', 'image_path')
    ### end Alembic commands ###
