"""Set non null values for columns

Revision ID: d782b5fe2eae
Revises: 0ec90e213dd1
Create Date: 2015-12-29 13:05:24.997173

"""

# revision identifiers, used by Alembic.
revision = 'd782b5fe2eae'
down_revision = '0ec90e213dd1'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('comments', 'chapter',
               existing_type=sa.VARCHAR(length=80),
               nullable=False)
    op.alter_column('comments', 'comment',
               existing_type=sa.VARCHAR(length=260),
               nullable=False)
    op.alter_column('comments', 'page',
               existing_type=sa.VARCHAR(length=80),
               nullable=False)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('comments', 'page',
               existing_type=sa.VARCHAR(length=80),
               nullable=True)
    op.alter_column('comments', 'comment',
               existing_type=sa.VARCHAR(length=260),
               nullable=True)
    op.alter_column('comments', 'chapter',
               existing_type=sa.VARCHAR(length=80),
               nullable=True)
    ### end Alembic commands ###
